/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CareerCard: typeof import('./src/components/CareerCard.vue')['default']
    CareerGraph: typeof import('./src/components/CareerGraph.vue')['default']
    CareerTree: typeof import('./src/components/CareerTree.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DocumentReader: typeof import('./src/components/DocumentReader.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JobDescriptionEditor: typeof import('./src/components/JobDescriptionEditor.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeBtn: typeof import('./src/components/themeBtn.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}

// For TSX support
declare global {
  const Badge: typeof import('primevue/badge')['default']
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const CareerCard: typeof import('./src/components/CareerCard.vue')['default']
  const CareerGraph: typeof import('./src/components/CareerGraph.vue')['default']
  const CareerTree: typeof import('./src/components/CareerTree.vue')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const Divider: typeof import('primevue/divider')['default']
  const DocumentReader: typeof import('./src/components/DocumentReader.vue')['default']
  const Editor: typeof import('primevue/editor')['default']
  const FileUpload: typeof import('primevue/fileupload')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const JobDescriptionEditor: typeof import('./src/components/JobDescriptionEditor.vue')['default']
  const Menubar: typeof import('primevue/menubar')['default']
  const Message: typeof import('primevue/message')['default']
  const MultiSelect: typeof import('primevue/multiselect')['default']
  const Nav: typeof import('./src/components/nav.vue')['default']
  const Navbar: typeof import('./src/components/navbar.vue')['default']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const Panel: typeof import('primevue/panel')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const TabPanel: typeof import('primevue/tabpanel')['default']
  const TabView: typeof import('primevue/tabview')['default']
  const Textarea: typeof import('primevue/textarea')['default']
  const ThemeBtn: typeof import('./src/components/themeBtn.vue')['default']
  const Toast: typeof import('primevue/toast')['default']
}