/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CareerCard: typeof import('./src/components/CareerCard.vue')['default']
    CareerGraph: typeof import('./src/components/CareerGraph.vue')['default']
    CareerTree: typeof import('./src/components/CareerTree.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    ThemeBtn: typeof import('./src/components/themeBtn.vue')['default']
  }
}
